### ISSUE TITLE
 FilterByOrientationBias fail on sample 18M11839

### ISSUE THREAD

**Issue by josephhalstead** [AWGL/SomaticEnrichment#10]
Sample pipeline failed on this sample. Possibly due to small number of variants in VCF.

Temporary workaround - just skipped this filtering step - all variants in sample already had different filters applied anyway so no change to end result.

Full Error:

java.lang.IllegalArgumentException: errorRateLog10 must be good probability but got NaN
	at org.broadinstitute.hellbender.utils.QualityUtils.phredScaleLog10ErrorRate(QualityUtils.java:321)
	at org.broadinstitute.hellbender.utils.QualityUtils.phredScaleErrorRate(QualityUtils.java:307)
	at org.broadinstitute.hellbender.tools.exome.orientationbiasvariantfilter.PreAdapterOrientationScorer.scoreOrientationBiasMetricsOverContext(PreAdapterOrientationScorer.java:78)
	at org.broadinstitute.hellbender.tools.exome.FilterByOrientationBias.onTraversalStart(FilterByOrientationBias.java:191)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:890)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by josephhalstead** [comment]
fixed in next release

**Comment by josephhalstead** [comment]
This occurred again in the NTC sample for run:

Could replace

```

if [ $(grep -v "#" "$seqId"_"$sampleId".vcf | grep -v '^ ' | wc -l) -ne 0 ]; then

    # variant filter
    ./SomaticEnrichmentLib-"$version"/variant_filter.sh $seqId $sampleId $panel $minBQS $minMQS $gatk4

    #annotation

    ./SomaticEnrichmentLib-"$version"/annotation.sh $seqId $sampleId $panel $gatk4
else
    mv "$seqId"_"$sampleId".vcf "$seqId"_"$sampleId"_filteredStrLeftAligned_annotated.vcf
fi

# generate variant reports
./SomaticEnrichmentLib-"$version"/hotspot_variants.sh $seqId $sampleId $panel $pipelineName $pipelineVersion

# run manta for all samples except NTC
if [ $sampleId != 'NTC' ]; then
    ./SomaticEnrichmentLib-"$version"/manta.sh $seqId $sampleId $panel $vendorPrimaryBed
fi

# add samplename to run-level file if vcf detected
if [ -e /data/results/$seqId/$panel/$sampleId/"$seqId"_"$sampleId"_filteredStrLeftAligned_annotated.vcf ]
then
    echo $sampleId >> /data/results/$seqId/$panel/sampleVCFs.txt
fi

# tidy up
#rm /data/results/$seqId/$panel/$sampleId/*.interval_list
#rm /data/results/$seqId/$panel/$sampleId/seqArtifacts.*
#rm /data/results/$seqId/$panel/$sampleId/getpileupsummaries.table
#rm /data/results/$seqId/$panel/$sampleId/calculateContamination.table

```
will open pul request
